### ISSUE TITLE
Difficulties using autocomplete tags - Web Application only

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#3] opened 2020-05-13 18:16 UTC
**Priority** - Medium
**Severity** - Low

**Description**
When creating a new task in the web application, I have difficulties using the autocomplete function for tags. I start typing and autocomplete is displayed, but when I click on it, there is no result. This does occur about 70-80% of the time. Sometimes it takes up to 8 clicks to actually choose the tag.
 
**To Reproduce**
**_Precondition:_** You must have existing active tickets with the same tag, that is going to be use for the test, to be able to reproduce the defect. 
1. Open web application
2. Click on + button
3. Click on the field before "Add Tag" 
4. Star typing the name of already existing tag
5. When the autocomplete option is displayed, click on it
6. Repeat steps 4 & 5 until tag is added

**Expected behavior**
The tag is chosen and automatically added.

**Actual Result**
The autocomplete suggestion disappears, and you have to click on the field to see it again.

**Screenshots**
![vokoscreen-2020-05-13_19-50-59](https://user-images.githubusercontent.com/65238833/81848834-614b2300-955e-11ea-8fab-6584b9adaeab.gif)

**Desktop**
 - Ubuntu 18.04 Bionic Beaver
 - Mozilla Firefox 
 - 76.0 (64-bit)
&
 - Chrome 
 -Version 81.0.4044.138 (Official Build) (64-bit)

**Smartphone:**
Does not occur

**Additional context**
Does not occur in Chromium (Version 81.0.4044.138 (Official Build) snap (64-bit))

**Comment by duy-a** [comment] 2020-05-14 03:30
Thank you for the gif illustrating the issue. I will have to investigate this a bit more, as this does not happen on my machine.

Do I understand correctly that it's only happening in Firefox browser?

**Comment by vpeycheva** [comment] 2020-05-14 06:51
It occur on both Firefox and Chrome, but not Chromium. I'll install a virtual machine with Windows and see if it occurs there.

**Comment by duy-a** [comment] 2020-05-14 07:17
Very interesting, as Chrome is using a chromium as a core, and based on your report they are the same version.

**Comment by vpeycheva** [comment] 2020-05-14 07:25
Yes, that confused me ass well. I'm using Ubuntu. Here is all the information Linux idea 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:32:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
What operation system are you using, and can the issue somehow linked to that. I'll try Window in about 6-7 hours, to see if I can replicate it there.

**Comment by duy-a** [comment] 2020-05-14 08:03
I am using browsers on Windows, MacOs, Android & iOS to test the web version. The issue never occurred.

Here is what you can do, on a browsers where the issue is happening
1. open the development tools
2. navigate to console tab
3. try to reproduce the error
4. If you can reproduce the error, see if there are any errors are coming out in console

If you cannot reproduce or there are no errors in console, then we can put aside this bug for now, until I receive other reports of the same issue, in order not to waste too much time.

**Comment by vpeycheva** [comment] 2020-05-14 08:21
Alpha:
![Screenshot from 2020-05-14 11-11-33](https://user-images.githubusercontent.com/65238833/81909974-094f0380-95d4-11ea-8569-0337df32eba5.png)
Beta:
![Screenshot from 2020-05-14 11-13-17](https://user-images.githubusercontent.com/65238833/81910018-1a981000-95d4-11ea-8890-6fc94f7dfc9d.png)
Warnings:
Some cookies are misusing the recommended “sameSite“ attribute 2
Cookie “_ga” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies js:97:879
Cookie “_ga_QM66M8N51G” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies js:97:879

An IndexedDB transaction that was not yet complete has been aborted due to page navigation. index.cjs.js:5738

ngx-autosize: textarea not found ngx-autosize.js:81

Some cookies are misusing the recommended “sameSite“ attribute 4
Cookie “_ga” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies js:97:879
Cookie “_ga_X9TB106G1J” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies js:97:879
Cookie “_ga” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies js:97:879
Cookie “_ga_X9TB106G1J” will be soon rejected because it has the “sameSite” attribute set to “none” or an invalid value, without the “secure” attribute. To know more about the “sameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Cookies js:97:879

An IndexedDB transaction that was not yet complete has been aborted due to page navigation. main-es2015.c14638ff1a4684780f87.js:1:148218

Errors:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://firestore.googleapis.com/google.firestore.v1.Firesto…vvJjID6wmDMWdZA&CI=0&AID=17&TYPE=xmlhttp&zx=o75oq64trak1&t=2. (Reason: CORS request did not succeed).

**Comment by duy-a** [comment] 2020-05-14 08:41
are you running your Ubuntu via a virtual machine?

**Comment by vpeycheva** [comment] 2020-05-14 08:45
No, the Ubuntu is my OS.

**Comment by duy-a** [comment] 2020-05-14 08:54
Here is what a quick research showed me.

> ..., but is a fundamental network error of some kind.
> 
> In many cases, it is caused by a browser plugin (e.g. an ad blocker or privacy protector) blocking the request.

I have ad blocker, so it is not a issue. I did notice your browser has a green shield icon as an extension. Could it be a privacy protection extension of some sort?

- If yes, can you pause it and retry again? Does the issue still happen?

- If it is not, I don't have a single clue, and will keep this bug open for a later investigation.

Thank you very much for helping me out to find a root cause.

**Comment by vpeycheva** [comment] 2020-05-14 09:06
I'm glad I could help. I disabled the addblock (with built in privacy protection), but the issue is still present.

**Comment by duy-a** [comment] 2020-05-14 09:18
I was able to reproduce this error by clicking the tag by clicking and holding the tag Basically, the autocomplete will disappear without adding it to the task, if you clicking the tag longer that a split second.

Please assist to verify this behavior by a quick click on the tag from autocomplete and then by pressing and holding.

**Comment by vpeycheva** [comment] 2020-05-14 09:24
Yes, when I click it and hold it, it disappears.

**Comment by duy-a** [comment] 2020-05-14 09:39
And if you click quickly on the tag, it will be added as expected?

**Comment by vpeycheva** [comment] 2020-05-14 09:44
If I do it quick (quicker that regular) it is added.

**Comment by duy-a** [comment] 2020-05-14 09:55
Awesome, thank you, I will try to issue the fix tonight. Thank you :)

**Comment by duy-a** [comment] 2020-05-14 15:31
The issue was both on web and android:
- that tags can be now added, regardless of how long it is pressed.

The fix has been released for both & only us you and I are receiving these updates on both versions:

- Alpha web: https://app.tododone.io/inbox
- Android: will take some time for the update be distributed

Will be waiting for the feedback & confirmation to release it to open beta.

**Comment by vpeycheva** [comment] 2020-05-14 19:32
The issue is no longer occurring.

**Comment by duy-a** [comment] 2020-05-15 01:45
All the fixes has been released to open beta. Thank you & closing the issue.

**Closed by duy-a** 2020-05-15 01:45 UTC
Labels: bug, need investigation
