### ISSUE TITLE
Wrong behavior of program while space character is used in tags

### ISSUE THREAD

**Issue by Viktoriia-Chumak** [duy-a/tobidun-issues#4] opened 2020-05-18 21:26 UTC
**Describe the bug**
Tag is not shown when it is added to the task and it consists space character only (while the task is editing). But this tag is shown on Menu page in "Tags" section. 

**To Reproduce**
1) Open program
2) Press '+' in Inbox page
3) Add new task 
4) Add tag to the task which consist of space character only
5) Save the task
6) Open Menu page
7) Sort tasks by tag
8) Open sorted task
9) There is no tag inside the task

**Expected behavior**
Tag should be shown when it is added to the task and it consists space character only. Or there should be error message that it is forbidden use only space character in tags.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei P20
 - OS: Android 9.0
 
![step1](https://user-images.githubusercontent.com/65408344/82261223-a8edf800-992c-11ea-987f-97e19f658ce6.jpg)
![step2](https://user-images.githubusercontent.com/65408344/82261225-a9868e80-992c-11ea-92fa-f71c3c95015c.jpg)
![step3](https://user-images.githubusercontent.com/65408344/82261227-a9868e80-992c-11ea-8214-61ddf140eb3d.jpg)
![step4](https://user-images.githubusercontent.com/65408344/82261228-aa1f2500-992c-11ea-8b70-1ddcaf4cb7b7.jpg)

**Comment by duy-a** [comment] 2020-05-19 02:20
Has been fixed in the current open beta version

**Comment by Viktoriia-Chumak** [comment] 2020-05-27 14:32
It doesn't work.

**Comment by duy-a** [comment] 2020-05-27 14:46
please assist to check if your app on the phone is updated. This is fixed already.

**Comment by Viktoriia-Chumak** [comment] 2020-05-27 14:59
App on the phone is updated, but problem is still appears.

**Comment by duy-a** [comment] 2020-05-27 15:20
I can't reproduce the issue on my phone, please assist to verify one more time that version of the app is v0.3 via the play store + you should see the updates as below:

![Screen Shot 2020-05-27 at 22 19 25](https://user-images.githubusercontent.com/20321464/83039293-2e2d8700-a068-11ea-95c6-1dd8b5ee5cc3.png)

**Comment by Viktoriia-Chumak** [comment] 2020-05-27 15:34
I double check  the version and it is the last. 
Side bar should not have section "Filters" and all new features work. 
I try to reproduce this issue (add tag which contain only space) and here is result.
![step1](https://user-images.githubusercontent.com/65408344/83041008-fb56a500-a00d-11ea-98bd-59f7f5585600.jpg)
![step2](https://user-images.githubusercontent.com/65408344/83041013-fbef3b80-a00d-11ea-9b98-7a7d899f265d.jpg)
![step3](https://user-images.githubusercontent.com/65408344/83041014-fc87d200-a00d-11ea-9626-843cf0fb64f6.jpg)

**Comment by duy-a** [comment] 2020-05-27 16:14
have released a hot fix, update should be available via google play store soon.

**Comment by Viktoriia-Chumak** [comment] 2020-06-01 19:08
It works correct now.

**Closed** 2020-06-02 05:18 UTC
Labels: bug
