### ISSUE TITLE
Unfinished sentence in Backers page - Very low priority

### ISSUE THREAD

**Issue by vpeycheva** [duy-a/tobidun-issues#2] opened 2020-05-13 16:46 UTC
The second in Backers page is not finished:

 "The app with its ongoing development made possible 100% entirely by the support aweseome people like you. If we helped you in any way or you want your name (or logo) displayed here, please consider" 

**To Reproduce**
Open this link:         https://tobidun.io/backers

**Or** for Android app
1 Open app
2 Open sidebar
3 Click on Made Possible By

**Expected behavior**
Second sentence is finished.

**Actual result**
Second sentence is not finished.

![Screenshot from 2020-05-13 19-30-55](https://user-images.githubusercontent.com/65238833/81840314-7c636600-9551-11ea-9b4f-b2d25c94886e.png)

Appears in both web application and android app, the device is irrelevant.

**Additional comment**
I know that this is very minor, but wanted to keep it in the correct template, as technically it is still a defect. If you want me to use the other template for that kind of bugs, let me know.

**Comment by duy-a** [comment] 2020-05-14 03:17
Hi, actually that's not a bug.  It supposed to be read as follow:

- ... displayed here, please consider: Become A Patron/ PayPal (those are the buttons below).

Thank you, I will think a on how to reword that sentence as I can see that it might cause some confusion.

**Comment by vpeycheva** [comment] 2020-05-14 07:06
You can finish it with "... supporting the project in the following ways:"
I believe that way it will be clearer, because the buttons are not visible on both alpha and beta web applications and Android application. I can only see the when I click on "I want to support the project" and get redirected to the site.

Alpha:
![webb app alpha](https://user-images.githubusercontent.com/65238833/81903380-5f1eae00-95ca-11ea-82e2-2de60bc32799.png)
Beta:
![webb app beta](https://user-images.githubusercontent.com/65238833/81903405-65ad2580-95ca-11ea-8a3c-c29c3ee24b2d.png)
Android:
![Screenshot_20200514-100142](https://user-images.githubusercontent.com/65238833/81903436-6e056080-95ca-11ea-8b56-fe7cfb467af2.png)

And here is the site where they can be seen:
![site](https://user-images.githubusercontent.com/65238833/81903495-81b0c700-95ca-11ea-9226-cc60b285b2fb.png)

**Comment by duy-a** [comment] 2020-05-14 07:15
That's a good suggestion, will update as per your suggestion.

Just for information, on android application, unfortunately, I cannot place the buttons the same way they are on the web, due to the Google's Policy regarding the payment.

Once it is update on both android & web will close this issue.

Thank you.

**Comment by duy-a** [comment] 2020-05-20 14:58
A fix has been released to alpha web & android version. Please assist to verify and close the issue if expected behavior is met.

**Comment by vpeycheva** [comment] 2020-05-20 17:06
It's fixed

**Closed** 2020-05-21 01:32 UTC
Labels: landing-website
